services:
  postgres:
    image: postgres:16
    container_name: payments-ledger-db
    environment:
      POSTGRES_DB: payments_ledger
      POSTGRES_USER: payments_user
      POSTGRES_PASSWORD: payments_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: