spring.application.name=payments-ledger
spring.datasource.url=jdbc:postgresql://localhost:5433/payments_ledger
spring.datasource.username=payments_user
spring.datasource.password=payments_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true